/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <sys/unistd.h>
/* Header for class com_aisaka_mmapdemo_MMAPOperate */

#ifndef _Included_com_aisaka_mmapdemo_MMAPOperate
#define _Included_com_aisaka_mmapdemo_MMAPOperate
#ifdef __cplusplus
extern "C" {
#endif
const int DEFAULT_MMAP_SIZE = getpagesize();
/*
 * Class:     com_aisaka_mmapdemo_MMAPOperate
 * Method:    exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_aisaka_mmapdemo_MMAPOperate_exit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_aisaka_mmapdemo_MMAPOperate
 * Method:    wirteString
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_aisaka_mmapdemo_MMAPOperate_wirteString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_aisaka_mmapdemo_MMAPOperate
 * Method:    readString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aisaka_mmapdemo_MMAPOperate_readString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_aisaka_mmapdemo_MMAPOperate
 * Method:    openFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_aisaka_mmapdemo_MMAPOperate_openFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
